language: bash

env:
  global:
  - secure: nkFbG9paJ+yqVUGih1MUIhlQAU+TtAYdmhMHigzCreHs2zkC9ge70ZvC6WG4aOe4tD6MJ4wmiDK8ofyfneQGivYlcRklujqSj2g74Uzfl9mBBuiLzmLIOX1SJkV4BBqGdKI5gyVi5vG3Rj/WIj+XP6C3OqyKZautgEJLlmJYmp+yevo5PyqEW9T+TwXY/AC1vRbTmWa4qgJYlqWCVzc5zHo6XqlHLpdNQ1+Am8nSK1Wa2eh+TbrNHoCJIZamyC/y4rn9wXR+mu3KQX/1Lks3FCTlm7SBgDUfGIlde0JqjWsxBiW+ghI7v8/dyCGoLYAQU0sgSB7EgkJMJSgq/BBVsCh/jXCy9nsoWqP31NRFCLP9NyCftODco7+ZkbctGHWG9WWEB6mMj3pUgwLzbfZrAJllo1u9BN93IHV2MQUwHMhIdmOECZAngVY5lHDc1KKRxJDLqulOpHksZ4Ybj7jN1PTy2GUfHT5hC+Sl658u3GQgH0eM8rUCzDIa/pH1UQQN9mH/dstiP+KCCCscAC+/a0m99B0ND5DNBZFLtCiZEqXmpErQDQkMnjZsdbjnd/mIkYXk36cWDY61bnBnzbxu4ZZysXy4HveomZ5ez25MA7YuAvwrBhMvgKA/01E+gW6/1sicMd7QY2o3cFhyXaaQG5yVK/bNHPUvJNEh8rpO6rA=
  - secure: nvoE7b/DZpzqmbxlnsIfKnTswr3UR+1CTu5JCCzJCL/XRctmh6epqZyyUC+qDyuEZY+fw9BNv47v5jhImf8IVGDe/XH7CC2IVN/etTvgDm12z2G5CfoLZqgKJ3kqnCXRuQRqD/lv7/F0AYgGWALqfxQDXvIDIuaoeKhtwrsAIJRKhuQQ/432FGJ2eLSueov4/L95mM546hHS1XSg3cTvLrCk8HFUETv8vHnpPKgrRrwQxwwRgxPvtLTCZnu4kA8TkpN12Zv13oKYYJABRmMNx/Co8nptghu61VsS7lrnW8bSUP7OPvkGvry8cOBF+zbsT5neFc92fYoAAGGnHTmjHtBAl4SYKyS5bIJz7VVTjK3GAjYUtbCvb5aDb1+2pIbAuayAFoGNS7AirCNJZabgCXU9W4G+JCWS1RZg63Jkqavf8pLfSA2FkLHc10pxULa+f8yAus0q9dGv//yBQJC+xe9lS/ELQm8DnYDpgd4xlcUChSXHycktWvVjSPp9gOav5mti5quUS/fnZFinY93C8iIi++oj4G7vaxG2PheaMj3mIhpdOhN+tCQ8zp7uf1yZ4ZqMor3OIC5jr2x/lQAP6UmR2HQvzwMQRW6ENQCSZSxER0TTV24g/lyKAR9hWr8zwCmsKb/sKucMhTg+fn/vAuE6Dx+B3aCu4pOxUp9UKzA=
  - COMMIT=${TRAVIS_COMMIT::8}

 after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=karrlein/phpmetrics-server
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

 notifications:
  slack: karrlein:an1enYrAJKdow0DYS4sSvoGC
